/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OEbMFSRj5FM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function AppPage() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header
        className="bg-gradient-to-r from-[#673AB7] to-[#512DA8] py-6 px-4 md:px-6">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <Link className="text-white font-bold text-2xl" href="#">
            Play Store
          </Link>
          <div className="relative w-full max-w-md">
            <Input
              className="bg-white/20 text-white placeholder:text-white/70 rounded-full py-2 px-4 pr-10 w-full focus:outline-none focus:ring-2 focus:ring-white focus:ring-opacity-50"
              placeholder="Search for apps and games"
              type="search" />
            <SearchIcon className="absolute right-3 top-1/2 -translate-y-1/2 w-5 h-5 text-white" />
          </div>
        </div>
      </header>
      <main className="flex-1 bg-gray-100 dark:bg-gray-900">
        <section className="py-8 px-4 md:px-6">
          <div className="max-w-6xl mx-auto">
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <img
                  alt="App Icon"
                  className="rounded-lg mb-4"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/400",
                    objectFit: "cover",
                  }}
                  width={400} />
                <div className="flex items-center mb-2">
                  <StarIcon className="w-5 h-5 fill-yellow-500" />
                  <span className="text-gray-600 dark:text-gray-400 ml-1">4.8</span>
                  <span className="text-gray-600 dark:text-gray-400 ml-2">(12.3K reviews)</span>
                </div>
                <h1 className="text-3xl font-bold mb-2 text-gray-800 dark:text-gray-200">Spotify</h1>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  Listen to millions of songs and podcasts for free.
                </p>
                <div className="flex items-center mb-4">
                  <DownloadIcon className="w-5 h-5 text-gray-600 dark:text-gray-400 mr-2" />
                  <span className="text-gray-600 dark:text-gray-400">1.2M downloads</span>
                </div>
                <Button className="w-full" size="lg">
                  Download
                </Button>
              </div>
              <div>
                <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
                  <h2 className="text-2xl font-bold mb-4 text-gray-800 dark:text-gray-200">About this app</h2>
                  <p className="text-gray-600 dark:text-gray-400 mb-4">
                    Spotify is a digital music, podcast, and video streaming service that gives you access to millions
                    of songs and other content from artists all over the world.
                  </p>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <h3 className="text-lg font-semibold mb-2 text-gray-800 dark:text-gray-200">Features</h3>
                      <ul className="list-disc pl-4 text-gray-600 dark:text-gray-400">
                        <li>Stream music and podcasts</li>
                        <li>Create and share playlists</li>
                        <li>Offline listening</li>
                        <li>Personalized recommendations</li>
                      </ul>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold mb-2 text-gray-800 dark:text-gray-200">Requirements</h3>
                      <ul className="list-disc pl-4 text-gray-600 dark:text-gray-400">
                        <li>Android 4.0 or later</li>
                        <li>Minimum 1GB RAM</li>
                        <li>Spotify account</li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mt-6">
                  <h2 className="text-2xl font-bold mb-4 text-gray-800 dark:text-gray-200">Reviews</h2>
                  <div className="space-y-4">
                    <div className="flex items-start">
                      <Avatar className="mr-4">
                        <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                        <AvatarFallback>JD</AvatarFallback>
                      </Avatar>
                      <div>
                        <div className="flex items-center mb-2">
                          <h3 className="font-semibold text-gray-800 dark:text-gray-200 mr-2">John Doe</h3>
                          <div className="flex items-center">
                            <StarIcon className="w-4 h-4 fill-yellow-500" />
                            <span className="text-gray-600 dark:text-gray-400 ml-1">4.8</span>
                          </div>
                        </div>
                        <p className="text-gray-600 dark:text-gray-400">
                          Spotify is an amazing app that has completely changed the way I listen to music. The selection
                          is incredible, and the personalized recommendations are spot on.
                        </p>
                      </div>
                    </div>
                    <div className="flex items-start">
                      <Avatar className="mr-4">
                        <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                        <AvatarFallback>SA</AvatarFallback>
                      </Avatar>
                      <div>
                        <div className="flex items-center mb-2">
                          <h3 className="font-semibold text-gray-800 dark:text-gray-200 mr-2">Sarah Anderson</h3>
                          <div className="flex items-center">
                            <StarIcon className="w-4 h-4 fill-yellow-500" />
                            <span className="text-gray-600 dark:text-gray-400 ml-1">4.7</span>
                          </div>
                        </div>
                        <p className="text-gray-600 dark:text-gray-400">
                          I've been using Spotify for years and it just keeps getting better. The app is easy to use,
                          the sound quality is great, and the selection of music and podcasts is unbeatable.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-gray-800 text-gray-400 py-6 px-4 md:px-6">
        <div
          className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between">
          <div className="mb-4 md:mb-0">
            <Link className="text-white font-bold text-2xl" href="#">
              Play Store
            </Link>
          </div>
          <nav>
            <ul className="flex flex-wrap justify-center">
              <li className="mr-4">
                <Link className="hover:text-white" href="#">
                  About
                </Link>
              </li>
              <li className="mr-4">
                <Link className="hover:text-white" href="#">
                  Developers
                </Link>
              </li>
              <li className="mr-4">
                <Link className="hover:text-white" href="#">
                  Support
                </Link>
              </li>
              <li>
                <Link className="hover:text-white" href="#">
                  Privacy
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </footer>
    </div>)
  );
}

function DownloadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}
