/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JZmCKd9Mukj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"

export function AppFeeds() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header
        className="bg-gradient-to-r from-[#673AB7] to-[#512DA8] py-6 px-4 md:px-6">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <Link className="text-white font-bold text-2xl" href="#">
            Play Store
          </Link>
          <div className="relative w-full max-w-md">
            <Input
              className="bg-white/20 text-white placeholder:text-white/70 rounded-full py-2 px-4 pr-10 w-full focus:outline-none focus:ring-2 focus:ring-white focus:ring-opacity-50"
              placeholder="Search for apps and games"
              type="search" />
            <SearchIcon className="absolute right-3 top-1/2 -translate-y-1/2 w-5 h-5 text-white" />
          </div>
        </div>
      </header>
      <main className="flex-1 bg-gray-100 dark:bg-gray-900">
        <section className="py-8 px-4 md:px-6">
          <div className="max-w-6xl mx-auto">
            <h2 className="text-2xl font-bold mb-4 text-gray-800 dark:text-gray-200">Featured Apps</h2>
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              <Card>
                <Link className="block" href="#">
                  <img
                    alt="App Icon"
                    className="rounded-lg mb-2"
                    height={100}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/100",
                      objectFit: "cover",
                    }}
                    width={100} />
                  <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-1">Spotify</h3>
                  <div className="flex items-center mb-2">
                    <StarIcon className="w-4 h-4 fill-yellow-500" />
                    <span className="text-gray-600 dark:text-gray-400 ml-1">4.8</span>
                  </div>
                  <Button size="sm">Download</Button>
                </Link>
              </Card>
              <Card>
                <Link className="block" href="#">
                  <img
                    alt="App Icon"
                    className="rounded-lg mb-2"
                    height={100}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/100",
                      objectFit: "cover",
                    }}
                    width={100} />
                  <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-1">Instagram</h3>
                  <div className="flex items-center mb-2">
                    <StarIcon className="w-4 h-4 fill-yellow-500" />
                    <span className="text-gray-600 dark:text-gray-400 ml-1">4.7</span>
                  </div>
                  <Button size="sm">Download</Button>
                </Link>
              </Card>
              <Card>
                <Link className="block" href="#">
                  <img
                    alt="App Icon"
                    className="rounded-lg mb-2"
                    height={100}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/100",
                      objectFit: "cover",
                    }}
                    width={100} />
                  <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-1">WhatsApp</h3>
                  <div className="flex items-center mb-2">
                    <StarIcon className="w-4 h-4 fill-yellow-500" />
                    <span className="text-gray-600 dark:text-gray-400 ml-1">4.9</span>
                  </div>
                  <Button size="sm">Download</Button>
                </Link>
              </Card>
              <Card>
                <Link className="block" href="#">
                  <img
                    alt="App Icon"
                    className="rounded-lg mb-2"
                    height={100}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/100",
                      objectFit: "cover",
                    }}
                    width={100} />
                  <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-1">TikTok</h3>
                  <div className="flex items-center mb-2">
                    <StarIcon className="w-4 h-4 fill-yellow-500" />
                    <span className="text-gray-600 dark:text-gray-400 ml-1">4.6</span>
                  </div>
                  <Button size="sm">Download</Button>
                </Link>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-8 px-4 md:px-6">
          <div className="max-w-6xl mx-auto">
            <h2 className="text-2xl font-bold mb-4 text-gray-800 dark:text-gray-200">Categories</h2>
            <div
              className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
              <Link
                className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4 flex flex-col items-center justify-center hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
                href="#">
                <GamepadIcon className="w-8 h-8 text-purple-500 mb-2" />
                <span className="text-gray-800 dark:text-gray-200 font-semibold">Games</span>
              </Link>
              <Link
                className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4 flex flex-col items-center justify-center hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
                href="#">
                <UsersIcon className="w-8 h-8 text-blue-500 mb-2" />
                <span className="text-gray-800 dark:text-gray-200 font-semibold">Social</span>
              </Link>
              <Link
                className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4 flex flex-col items-center justify-center hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
                href="#">
                <BriefcaseIcon className="w-8 h-8 text-green-500 mb-2" />
                <span className="text-gray-800 dark:text-gray-200 font-semibold">Productivity</span>
              </Link>
              <Link
                className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4 flex flex-col items-center justify-center hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
                href="#">
                <FilmIcon className="w-8 h-8 text-red-500 mb-2" />
                <span className="text-gray-800 dark:text-gray-200 font-semibold">Entertainment</span>
              </Link>
              <Link
                className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4 flex flex-col items-center justify-center hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
                href="#">
                <BookOpenIcon className="w-8 h-8 text-yellow-500 mb-2" />
                <span className="text-gray-800 dark:text-gray-200 font-semibold">Education</span>
              </Link>
              <Link
                className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4 flex flex-col items-center justify-center hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
                href="#">
                <SmileIcon className="w-8 h-8 text-pink-500 mb-2" />
                <span className="text-gray-800 dark:text-gray-200 font-semibold">Lifestyle</span>
              </Link>
            </div>
          </div>
        </section>
        <section className="py-8 px-4 md:px-6">
          <div className="max-w-6xl mx-auto">
            <h2 className="text-2xl font-bold mb-4 text-gray-800 dark:text-gray-200">Top Charts</h2>
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              <Card>
                <Link className="block" href="#">
                  <img
                    alt="App Icon"
                    className="rounded-lg mb-2"
                    height={100}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/100",
                      objectFit: "cover",
                    }}
                    width={100} />
                  <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-1">Spotify</h3>
                  <div className="flex items-center mb-2">
                    <StarIcon className="w-4 h-4 fill-yellow-500" />
                    <span className="text-gray-600 dark:text-gray-400 ml-1">4.8</span>
                  </div>
                  <Button size="sm">Download</Button>
                </Link>
              </Card>
              <Card>
                <Link className="block" href="#">
                  <img
                    alt="App Icon"
                    className="rounded-lg mb-2"
                    height={100}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/100",
                      objectFit: "cover",
                    }}
                    width={100} />
                  <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-1">Instagram</h3>
                  <div className="flex items-center mb-2">
                    <StarIcon className="w-4 h-4 fill-yellow-500" />
                    <span className="text-gray-600 dark:text-gray-400 ml-1">4.7</span>
                  </div>
                  <Button size="sm">Download</Button>
                </Link>
              </Card>
              <Card>
                <Link className="block" href="#">
                  <img
                    alt="App Icon"
                    className="rounded-lg mb-2"
                    height={100}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/100",
                      objectFit: "cover",
                    }}
                    width={100} />
                  <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-1">WhatsApp</h3>
                  <div className="flex items-center mb-2">
                    <StarIcon className="w-4 h-4 fill-yellow-500" />
                    <span className="text-gray-600 dark:text-gray-400 ml-1">4.9</span>
                  </div>
                  <Button size="sm">Download</Button>
                </Link>
              </Card>
              <Card>
                <Link className="block" href="#">
                  <img
                    alt="App Icon"
                    className="rounded-lg mb-2"
                    height={100}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/100",
                      objectFit: "cover",
                    }}
                    width={100} />
                  <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-1">TikTok</h3>
                  <div className="flex items-center mb-2">
                    <StarIcon className="w-4 h-4 fill-yellow-500" />
                    <span className="text-gray-600 dark:text-gray-400 ml-1">4.6</span>
                  </div>
                  <Button size="sm">Download</Button>
                </Link>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-gray-800 text-gray-400 py-6 px-4 md:px-6">
        <div
          className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between">
          <div className="mb-4 md:mb-0">
            <Link className="text-white font-bold text-2xl" href="#">
              Play Store
            </Link>
          </div>
          <nav>
            <ul className="flex flex-wrap justify-center">
              <li className="mr-4">
                <Link className="hover:text-white" href="#">
                  About
                </Link>
              </li>
              <li className="mr-4">
                <Link className="hover:text-white" href="#">
                  Developers
                </Link>
              </li>
              <li className="mr-4">
                <Link className="hover:text-white" href="#">
                  Support
                </Link>
              </li>
              <li>
                <Link className="hover:text-white" href="#">
                  Privacy
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </footer>
    </div>)
  );
}

function BookOpenIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
      <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
    </svg>)
  );
}


function BriefcaseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>)
  );
}


function FilmIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M7 3v18" />
      <path d="M3 7.5h4" />
      <path d="M3 12h18" />
      <path d="M3 16.5h4" />
      <path d="M17 3v18" />
      <path d="M17 7.5h4" />
      <path d="M17 16.5h4" />
    </svg>)
  );
}


function GamepadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="6" x2="10" y1="12" y2="12" />
      <line x1="8" x2="8" y1="10" y2="14" />
      <line x1="15" x2="15.01" y1="13" y2="13" />
      <line x1="18" x2="18.01" y1="11" y2="11" />
      <rect width="20" height="12" x="2" y="6" rx="2" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function SmileIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 2 4-2 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}


function UsersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  );
}
